
exports.phrases = [
  "Click here to learn the trade secrets <i>THEY</i> aren't telling you.",
  "Professional Networkers Hate Her! This Local Mom Came Up With Optimal Strategies for Connecting with the Skills YOU Need.",
  "95% of Would-Be Networkers Make This Mistake. Click Here To Learn What Not To Do When Searching For Professional Connections For Your Start Up",
  "Got A Concept And Need Coders? Click Here To Get In Contact With The Best of the Best",
  "Be Great At What You Do! Get Access to the Resources You Need To Be The Professional You Know You Can Become",
  "Overcome Your Shyness and Access The Skills Others Have to Offer with These Hot Tips",
  "Sign Up For Daily Insights In Making Your Activities More Productive",
  "Diversify Your Business Models And Access Untapped Revenue Streams",
  "Enter The Chatroom to Exchange Skills and Contacts With Fellow Networkers",
  "Addicted to Networking? Click Here To Get In Contact With Fellow Networking Addicts",
  "Free Web Seminar On Making Connections And Envisioning Your Professional Networks",
  "Click Here to Learn The Shocking Truth About LinkedIn Founder Reid Hoffman",
  "Networking Online is the Key to Building the Professional Contacts You Need to Succeed—Download this Set of Buisness Oriented Emoticons To Get In With the E-Crowd",
  "Are Your Professional Contacts Bots? Click Here to Get the Skinny On Predatory Networking Scams",
  "Hungry For a Human Touch? Meet Lonely Professionals In Your Area",
  "Learn The Five 'E's of Professional Networking",
  "Want To Ingratiate Yourself With That Hip Man iN the Office Who Always Knows What's Up? Now You Can. Online. So You Don't Have To face Rejection Head ON",
  "Don't let who you are get in the way of how your colleages perceive you. Learn the strategies today",
  "LinkedIn's  not going to cut it anymore. Learn to optimize what they won't teach you in business school.",
  "Life Hacks and More. Turn your life into a game -- a game you can win.",
  "Don't get cheated by those who actually <i>know</i> the secrets. You deserve a piece of the pie.",
  "If you're sleeping for more than 3 hours, you aren't going to suceed. Learn how we succeed.",
  "You can transform any social activity into a networking opportunity - We guarantee it.",
  "You can talk about the weather, or you can talk about stocks. Learn which one will optimize your future.",
  "SLip it in. How to fake it without seeming like a fake. Become elite.",
  "Elite techniques to transform a hobby into a career -- its not fun and games until there's profit involved.",
  "Zuckerberg's a dinosaur. Find out how to make an app that matters, an app that profits.",
  "You can play around or you can grow up and start earning. Click here to grow up",
  "Code is only part of the solution. Become one of the elite - artists, thinkers, innovators, ideas.",
  "Sell your ideas to suburban tweens, and let them handle the nerd grunting",
  "Just Because We Know How To NetWork Doesn't Mean We ForGot The Little People - find out how.",
  "An idea can become profit just like that - learn how not to let the other guy earn YOUR cash.",
  "Drive the traffic your business needs to achieve self-reliance.",
  "Search Engine Optimization (SEO) is how the Future can be Built. Don't let your antiquated techniques keep you in the dark",
  "StartUps aren't just smart - they are savory. Bet you wanna work at one? Good luck without clicking this",
  "Found a StartUp, Become a Hero",
  "StartUps are like bug-lights for smart people - learn to earn their respect (it WONT come easy)",
  "There's something about dedication and drive that drives the highest achievers - click to see just what that is",
  "It's not what you know, its who you know. Learn to know who to know",
  "Need To Make Small Talk In a Business Setting? Learn The Tricks of the Trade for Seeming Like A Well-Rounded Person"
];

exports.images = [
  'images/networking/1.jpg',
  'images/networking/2.jpg',
  'images/networking/3.jpg',
  'images/networking/4.jpg',
  'images/networking/5.jpg',
  'images/networking/6.jpg',
  'images/networking/7.png',
  'images/networking/8.jpg',
  'images/networking/9.jpg',
  'images/networking/10.jpg',
  'images/networking/11.jpg',
  'images/networking/12.jpg',
  'images/networking/13.jpg',
  'images/networking/14.jpg'
];
